// <auto-generated />
namespace T1809E.SEM3.P102_Team05.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202005020544277_update_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
